import { gitText as git, runGitRaw } from "./git-cli.mjs";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import { readFrontmatter, skillMetadata } from "./skill-metadata.mjs";

const MARKER = ".krn-export.json";
const BUDGET = 8000;

function directoryDigest(directory) {
  const hash = crypto.createHash("sha256");
  const walk = (dir) =>
    fs
      .readdirSync(dir, { withFileTypes: true })
      .sort((left, right) => left.name.localeCompare(right.name))
      .flatMap((entry) => {
        const full = path.join(dir, entry.name);
        return entry.isDirectory() ? walk(full) : [[path.relative(directory, full).split(path.sep).join("/"), full]];
      });
  for (const [relativePath, file] of walk(directory)) {
    hash.update(relativePath);
    hash.update("\0");
    hash.update(fs.readFileSync(file));
    hash.update("\0");
  }
  return hash.digest("hex");
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function harnessCommit(source) {
  const head = git(source, ["rev-parse", "HEAD"]);
  if (head) return head;
  const release = path.join(source, ".krn-release.json");
  if (fs.existsSync(release)) return readJson(release).commit;
  throw new Error(`harness source has no git HEAD or release metadata: ${source}`);
}

function upstreamSource(lock) {
  const source = lock.sources.find((candidate) => candidate.id === "mattpocock/skills");
  if (!source) throw new Error("config/upstream-sources.json is missing the mattpocock/skills pin");
  return source;
}

function defaultUpstreamPath(lock, home = process.env.HOME) {
  const source = upstreamSource(lock);
  return path.join(home, ".cache", "krn-upstream", source.id.replace("/", "-"));
}

function renderCatalog({ skills, krnCommit, upstream }) {
  const rows = skills
    .map((skill) => `| \`${skill.name}\` | ${skill.origin} | ${skill.description.replace(/\|/g, "\\|")} |`)
    .join("\n");
  return `# Development skill set

Generated by \`krn-codex skills export\`; do not edit by hand. Regenerate from the pinned sources.

- \`krn-codex-skills\` at \`${krnCommit}\`
- \`${upstream.id}\` at \`${upstream.commit}\` (MIT, see \`UPSTREAM-LICENSE\`)

| Skill | Origin | Description |
|---|---|---|
${rows}

## Skill-set contract

- Every skill directory has \`SKILL.md\` with frontmatter \`name\` equal to the
  directory name and a non-empty \`description\`, plus \`agents/openai.yaml\`.
- The initial-list budget is the sum of \`name + description\` characters for
  every skill and must stay within ${BUDGET} characters. When it grows past the
  budget, split scopes with nested \`.agents/skills\` directories, prune, or set
  \`allow_implicit_invocation: false\`.

Gate: \`krn-codex skills check --root .\`
`;
}

export function exportSkills({ source, upstream, root }) {
  if (!source || !root) throw new Error("skills export requires the harness source and the destination root");
  const finalDir = path.join(root, ".agents", "skills");
  const manifest = readJson(path.join(source, "skills", "manifest.json"));
  const lock = readJson(path.join(source, "config", "upstream-sources.json"));
  const upstreamPin = upstreamSource(lock);

  const resolvedUpstream = upstream ?? defaultUpstreamPath(lock);
  if (!fs.existsSync(path.join(resolvedUpstream, ".git"))) {
    throw new Error(
      `upstream checkout missing at ${resolvedUpstream}; clone it with: git clone ${upstreamPin.repository} ${resolvedUpstream} && git -C ${resolvedUpstream} checkout ${upstreamPin.commit}`,
    );
  }
  const upstreamHead = git(resolvedUpstream, ["rev-parse", "HEAD"]);
  if (upstreamHead !== upstreamPin.commit) {
    throw new Error(`upstream checkout is at ${upstreamHead || "unknown"}, expected ${upstreamPin.commit}`);
  }
  const upstreamDirty = git(resolvedUpstream, ["status", "--porcelain", "--untracked-files=no"]);
  if (upstreamDirty) {
    throw new Error(`upstream checkout has uncommitted changes; export from the pinned revision`);
  }
  const harnessPaths = Array.isArray(upstreamPin.harness_paths) && upstreamPin.harness_paths.length > 0
    ? upstreamPin.harness_paths
    : upstreamPin.required_paths;
  const harnessDirs = [...new Set(harnessPaths.map((required) => path.dirname(required)))];
  const upstreamStatus = runGitRaw(resolvedUpstream, ["status", "--porcelain", "-z", "--untracked-files=all", "--ignored=matching"]).out;
  const untracked = upstreamStatus
    .split("\0")
    .filter((entry) => entry.startsWith("?? ") || entry.startsWith("!! "))
    .map((entry) => entry.slice(3));
  const stray = untracked.find((file) => harnessDirs.some((dir) => file === dir || file.startsWith(`${dir}/`)));
  if (stray) {
    throw new Error(`upstream harness path contains an untracked file (${stray}); the pinned revision cannot reproduce exported bytes`);
  }
  const krnCommit = harnessCommit(source);
  const manifestSkills = Array.isArray(manifest.harness_skills) && manifest.harness_skills.length > 0
    ? manifest.skills.filter((skill) => manifest.harness_skills.includes(skill.name))
    : manifest.skills;
  const sourceSkillDirs = manifestSkills.map((skill) => skill.path);
  const sourceStatus = runGitRaw(source, ["status", "--porcelain", "-z", "--untracked-files=all", "--ignored=matching"]).out;
  const sourceEntries = sourceStatus.split("\0").filter(Boolean);
  const sourceDirty = sourceEntries.some((entry) => {
    if (entry.startsWith("?? ") || entry.startsWith("!! ")) return false;
    const file = entry.slice(3).trim();
    return sourceSkillDirs.some((dir) => file === dir || file.startsWith(`${dir}/`));
  });
  const sourceStray = sourceEntries
    .filter((entry) => entry.startsWith("?? ") || entry.startsWith("!! "))
    .map((entry) => entry.slice(3))
    .find((file) => sourceSkillDirs.some((dir) => file.startsWith(`${dir}/`)));
  if (sourceStray) {
    throw new Error(`source skill path contains an untracked or ignored file (${sourceStray}); it would be exported without provenance`);
  }

  const skillsDir = `${finalDir}.staging-${process.pid}-${Date.now()}`;
  let preserved = null;
  if (fs.existsSync(finalDir)) {
    const marker = path.join(finalDir, MARKER);
    if (!fs.existsSync(marker)) {
      throw new Error(`${finalDir} exists without ${MARKER}; refusing to overwrite foreign content`);
    }
    preserved = `${finalDir}.backup-${process.pid}-${Date.now()}`;
  }
  fs.rmSync(skillsDir, { recursive: true, force: true });
  fs.mkdirSync(skillsDir, { recursive: true });

  const skills = [];
  try {
  for (const skill of manifestSkills) {
    const relative = skill.path;
    fs.cpSync(path.join(source, relative), path.join(skillsDir, skill.name), { recursive: true, dereference: true });
    skills.push({ name: skill.name, origin: "krn", description: skillMetadata(path.join(source, relative, "SKILL.md"))?.description ?? "" });
  }
  const harnessPathsUsed = harnessPaths;
  for (const required of harnessPathsUsed) {
    const relative = path.dirname(required);
    const name = path.basename(relative);
    fs.cpSync(path.join(resolvedUpstream, relative), path.join(skillsDir, name), { recursive: true, dereference: true });
    skills.push({ name, origin: "upstream", description: skillMetadata(path.join(resolvedUpstream, relative, "SKILL.md"))?.description ?? "" });
  }
  const license = path.join(resolvedUpstream, "LICENSE");
  if (fs.existsSync(license)) fs.copyFileSync(license, path.join(skillsDir, "UPSTREAM-LICENSE"));
  const digests = Object.fromEntries(
      skills.map((skill) => [skill.name, directoryDigest(path.join(skillsDir, skill.name))]),
    );

    fs.writeFileSync(
      path.join(skillsDir, "README.md"),
      renderCatalog({ skills, krnCommit, upstream: { id: upstreamPin.id, commit: upstreamPin.commit } }),
    );
    fs.writeFileSync(
      path.join(skillsDir, MARKER),
      `${JSON.stringify(
        {
          schemaVersion: 1,
          krn: { commit: krnCommit, dirty: sourceDirty },
          upstream: { id: upstreamPin.id, commit: upstreamPin.commit },
          skills: skills.map((skill) => skill.name).sort(),
          digests,
        },
        null,
        2,
      )}\n`,
    );
  } catch (error) {
    fs.rmSync(skillsDir, { recursive: true, force: true });
    throw error;
  }
  try {
    if (preserved) fs.renameSync(finalDir, preserved);
    fs.renameSync(skillsDir, finalDir);
  } catch (error) {
    if (preserved) {
      if (!fs.existsSync(finalDir)) fs.renameSync(preserved, finalDir);
      else fs.rmSync(preserved, { recursive: true, force: true });
    }
    fs.rmSync(skillsDir, { recursive: true, force: true });
    throw error;
  }
  if (preserved) {
    try { fs.rmSync(preserved, { recursive: true, force: true }); } catch { /* the new export is already installed; a cleanup failure must not fail the call */ }
  }

  return { root, skillsDir: finalDir, skills: skills.length, krnCommit, upstreamCommit: upstreamPin.commit };
}

export function checkSkills({ root }) {
  const errors = [];
  const warnings = [];
  const skillsDir = path.join(root, ".agents", "skills");
  if (!fs.existsSync(skillsDir)) {
    return { root, skills: 0, budget: 0, errors: ["`.agents/skills` is missing"], warnings };
  }
  const markerFile = path.join(skillsDir, MARKER);
  if (!fs.existsSync(markerFile)) {
    errors.push(`\`${MARKER}\` is missing; this directory is not a generated export`);
  }
  const marker = (() => {
    if (!fs.existsSync(markerFile)) return null;
    try { return readJson(markerFile); } catch { errors.push(`.agents/skills/${MARKER} is not valid JSON`); return null; }
  })();
  const sourceByName = new Map();
  const sourceManifest = path.join(root, "skills", "manifest.json");
  const rootManifest = (() => {
    if (!fs.existsSync(sourceManifest)) return null;
    try { return readJson(sourceManifest); } catch { errors.push("skills/manifest.json is not valid JSON"); return null; }
  })();
  for (const skill of rootManifest?.skills ?? []) {
    sourceByName.set(skill.name, path.join(root, skill.path));
  }
  const directoriesMatch = (sourceDir, exportDir) => {
    const walk = (directory, base) =>
      fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
        const full = path.join(directory, entry.name);
        return entry.isDirectory() ? walk(full, base) : [path.relative(base, full)];
      });
    const sourceFiles = walk(sourceDir, sourceDir).sort();
    const exportFiles = walk(exportDir, exportDir).sort();
    if (JSON.stringify(sourceFiles) !== JSON.stringify(exportFiles)) return false;
    return sourceFiles.every((relative) =>
      fs.readFileSync(path.join(sourceDir, relative)).equals(fs.readFileSync(path.join(exportDir, relative))),
    );
  };
  const reproducesFromCommit = (relativeDir, commit, directory) => {
    const walk = (dir) =>
      fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
        const full = path.join(dir, entry.name);
        return entry.isDirectory() ? walk(full) : [path.relative(directory, full).split(path.sep).join("/")];
      });
    return walk(directory).every((relative) => {
      const recorded = git(root, ["rev-parse", `${commit}:${relativeDir}/${relative}`]);
      const actual = git(root, ["hash-object", path.join(relativeDir, relative)]);
      return recorded !== "" && actual !== "" && recorded === actual;
    });
  };
  let total = 0;
  let count = 0;
  const names = [];
  for (const entry of fs.readdirSync(skillsDir, { withFileTypes: true }).sort((left, right) => left.name.localeCompare(right.name))) {
    if (!entry.isDirectory()) continue;
    count += 1;
    names.push(entry.name);
    const dir = path.join(skillsDir, entry.name);
    const skillFile = path.join(dir, "SKILL.md");
    if (!fs.existsSync(skillFile)) {
      errors.push(`${entry.name}: missing SKILL.md`);
      continue;
    }
    const fields = skillMetadata(skillFile);
    if (!fields?.name || !fields?.description) {
      errors.push(`${entry.name}: SKILL.md needs name and description frontmatter`);
      continue;
    }
    if (fields.name !== entry.name) errors.push(`${entry.name}: frontmatter name "${fields.name}" must equal the directory name`);
    const sourceDir = sourceByName.get(entry.name);
    if (sourceDir && fs.existsSync(sourceDir)) {
      if (!directoriesMatch(sourceDir, dir)) {
        errors.push(`${entry.name}: exported files differ from source; run \`krn-codex skills export\``);
      }
      const relativeDir = path.relative(root, sourceDir).split(path.sep).join("/");
      if (marker?.krn?.commit && !marker.krn.dirty && relativeDir && !relativeDir.startsWith("..")
        && git(root, ["rev-parse", "--verify", `${marker.krn.commit}^{commit}`]) !== ""
        && !reproducesFromCommit(relativeDir, marker.krn.commit, dir)) {
        errors.push(`${entry.name}: exported files do not reproduce from marker commit ${marker.krn.commit}; re-export from a clean checkout`);
      }
    }
    const recorded = marker?.digests?.[entry.name];
    if (!recorded) {
      errors.push(`${entry.name}: export marker has no recorded digest; run \`krn-codex skills export\``);
    } else if (directoryDigest(dir) !== recorded) {
      errors.push(`${entry.name}: exported files changed since export; run \`krn-codex skills export\``);
    }
    if (!fs.existsSync(path.join(dir, "agents", "openai.yaml"))) errors.push(`${entry.name}: missing agents/openai.yaml`);
    total += fields.name.length + fields.description.length;
    if (fields.description.length > 280 && sourceByName.has(entry.name)) {
      warnings.push(`${entry.name}: description is ${fields.description.length} chars (informational; KRN-owned skills stay within 280)`);
    }
  }
  if (total > BUDGET) errors.push(`skill list costs ${total} characters of ${BUDGET}; prune, split scopes, or set allow_implicit_invocation: false`);
  const harness = Array.isArray(rootManifest?.harness_skills) && rootManifest.harness_skills.length > 0 ? rootManifest.harness_skills : null;
  if (harness) {
    const krnExported = names.filter((name) => sourceByName.has(name)).sort();
    const expected = [...harness].sort();
    if (JSON.stringify(krnExported) !== JSON.stringify(expected)) {
      errors.push(`exported krn skills [${krnExported.join(", ")}] must equal manifest.harness_skills [${expected.join(", ")}]; run \`krn-codex skills export\``);
    }
  }
  const lockFile = path.join(root, "config", "upstream-sources.json");
  const lock = (() => {
    if (!fs.existsSync(lockFile)) return null;
    try { return readJson(lockFile); } catch { errors.push("config/upstream-sources.json is not valid JSON"); return null; }
  })();
  if (lock) {
    const sources = Array.isArray(lock.sources) ? lock.sources : [];
    const upstreamPin = sources.find((source) => source && (marker?.upstream?.id ? source.id === marker.upstream.id : source.id === "mattpocock/skills"))
      ?? sources[0] ?? null;
    const upstreamExpected = [...new Set(
      (Array.isArray(upstreamPin?.harness_paths) && upstreamPin.harness_paths.length > 0 ? upstreamPin.harness_paths : Array.isArray(upstreamPin?.required_paths) ? upstreamPin.required_paths : [])
        .filter((requiredPath) => typeof requiredPath === "string")
        .map((requiredPath) => path.basename(path.dirname(requiredPath))),
    )].sort();
    const upstreamExported = names.filter((name) => !sourceByName.has(name)).sort();
    if (JSON.stringify(upstreamExported) !== JSON.stringify(upstreamExpected)) {
      errors.push(`exported upstream skills [${upstreamExported.join(", ")}] must equal the pinned harness_paths [${upstreamExpected.join(", ")}]; run \`krn-codex skills export\``);
    }
  }
  const catalogFile = path.join(skillsDir, "README.md");
  const catalog = fs.existsSync(catalogFile) ? fs.readFileSync(catalogFile, "utf8") : "";
  if (!catalog) errors.push(".agents/skills/README.md is missing");
  if (marker) {
    if (marker.krn?.dirty) {
      warnings.push(".agents/skills was exported from a dirty source; re-export from a clean checkout for a reproducible release");
    }
    for (const pin of [marker.krn?.commit, marker.upstream?.commit]) {
      if (!pin || !catalog.includes(pin)) errors.push(`.agents/skills/README.md is missing provenance pin ${pin ?? "?"}`);
    }
    const expected = [...(marker.skills ?? [])].sort();
    const actual = [...names].sort();
    if (marker.skills && JSON.stringify(actual) !== JSON.stringify(expected)) {
      errors.push(`marker lists [${expected.join(", ")}] but the directory holds [${actual.join(", ")}]`);
    }
    if (marker.upstream && lock) {
      const pin = (Array.isArray(lock.sources) ? lock.sources : []).find((source) => source && source.id === marker.upstream.id);
      if (pin && pin.commit !== marker.upstream.commit) {
        errors.push(`export marker records ${marker.upstream.id}@${marker.upstream.commit} but config/upstream-sources.json pins @${pin.commit}; run \`krn-codex skills export\``);
      }
    }
  }
  if (!fs.existsSync(path.join(skillsDir, "UPSTREAM-LICENSE"))) errors.push(".agents/skills/UPSTREAM-LICENSE is missing");

  return { root, skills: count, budget: total, errors, warnings };
}
