import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const MARKER = ".krn-export.json";
const BUDGET = 8000;

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function git(root, args) {
  try {
    return execFileSync("git", ["-C", root, ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
  } catch {
    return "";
  }
}

function harnessCommit(source) {
  const head = git(source, ["rev-parse", "HEAD"]);
  if (head) return head;
  const release = path.join(source, ".krn-release.json");
  if (fs.existsSync(release)) return readJson(release).commit;
  throw new Error(`harness source has no git HEAD or release metadata: ${source}`);
}

function frontmatter(file) {
  const text = fs.readFileSync(file, "utf8");
  const match = text.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  return Object.fromEntries(
    [...match[1].matchAll(/^(name|description):\s*(.+)$/gm)].map(([, key, value]) => [key, value.trim().replace(/^["']|["']$/g, "")]),
  );
}

function upstreamSource(lock) {
  const source = lock.sources.find((candidate) => candidate.id === "mattpocock/skills");
  if (!source) throw new Error("config/upstream-sources.json is missing the mattpocock/skills pin");
  return source;
}

export function defaultUpstreamPath(lock, home = process.env.HOME) {
  const source = upstreamSource(lock);
  return path.join(home, ".cache", "krn-upstream", source.id.replace("/", "-"));
}

function renderCatalog({ skills, krnCommit, upstream }) {
  const rows = skills
    .map((skill) => `| \`${skill.name}\` | ${skill.origin} | ${skill.description.replace(/\|/g, "\\|")} |`)
    .join("\n");
  return `# Development skill set

Generated by \`krn-codex skills export\`; do not edit by hand. Regenerate from the pinned sources.

- \`krn-codex-skills\` at \`${krnCommit}\`
- \`${upstream.id}\` at \`${upstream.commit}\` (MIT, see \`UPSTREAM-LICENSE\`)

| Skill | Origin | Description |
|---|---|---|
${rows}

## Skill-set contract

- Every skill directory has \`SKILL.md\` with frontmatter \`name\` equal to the
  directory name and a non-empty \`description\`, plus \`agents/openai.yaml\`.
- The initial-list budget is the sum of \`name + description\` characters for
  every skill and must stay within ${BUDGET} characters. When it grows past the
  budget, split scopes with nested \`.agents/skills\` directories, prune, or set
  \`allow_implicit_invocation: false\`.

Gate: \`krn-codex skills check --root .\`
`;
}

export function exportSkills({ source, upstream, root }) {
  if (!source || !root) throw new Error("skills export requires the harness source and the destination root");
  const skillsDir = path.join(root, ".agents", "skills");
  const manifest = readJson(path.join(source, "skills", "manifest.json"));
  const lock = readJson(path.join(source, "config", "upstream-sources.json"));
  const upstreamPin = upstreamSource(lock);

  const resolvedUpstream = upstream ?? defaultUpstreamPath(lock);
  if (!fs.existsSync(path.join(resolvedUpstream, ".git"))) {
    throw new Error(
      `upstream checkout missing at ${resolvedUpstream}; clone it with: git clone ${upstreamPin.repository} ${resolvedUpstream} && git -C ${resolvedUpstream} checkout ${upstreamPin.commit}`,
    );
  }
  const upstreamHead = git(resolvedUpstream, ["rev-parse", "HEAD"]);
  if (upstreamHead !== upstreamPin.commit) {
    throw new Error(`upstream checkout is at ${upstreamHead || "unknown"}, expected ${upstreamPin.commit}`);
  }
  const krnCommit = harnessCommit(source);

  if (fs.existsSync(skillsDir)) {
    const marker = path.join(skillsDir, MARKER);
    if (!fs.existsSync(marker)) {
      throw new Error(`${skillsDir} exists without ${MARKER}; refusing to overwrite foreign content`);
    }
    fs.rmSync(skillsDir, { recursive: true, force: true });
  }
  fs.mkdirSync(skillsDir, { recursive: true });

  const skills = [];
  for (const skill of manifest.skills) {
    const relative = skill.path;
    fs.cpSync(path.join(source, relative), path.join(skillsDir, skill.name), { recursive: true, dereference: true });
    skills.push({ name: skill.name, origin: "krn", description: frontmatter(path.join(source, relative, "SKILL.md"))?.description ?? "" });
  }
  for (const required of upstreamPin.required_paths) {
    const relative = path.dirname(required);
    const name = path.basename(relative);
    fs.cpSync(path.join(resolvedUpstream, relative), path.join(skillsDir, name), { recursive: true, dereference: true });
    skills.push({ name, origin: "upstream", description: frontmatter(path.join(resolvedUpstream, relative, "SKILL.md"))?.description ?? "" });
  }
  const license = path.join(resolvedUpstream, "LICENSE");
  if (fs.existsSync(license)) fs.copyFileSync(license, path.join(skillsDir, "UPSTREAM-LICENSE"));

  fs.writeFileSync(
    path.join(skillsDir, "README.md"),
    renderCatalog({ skills, krnCommit, upstream: { id: upstreamPin.id, commit: upstreamPin.commit } }),
  );
  fs.writeFileSync(
    path.join(skillsDir, MARKER),
    `${JSON.stringify(
      {
        schemaVersion: 1,
        krn: { commit: krnCommit },
        upstream: { id: upstreamPin.id, commit: upstreamPin.commit },
        skills: skills.map((skill) => skill.name).sort(),
      },
      null,
      2,
    )}\n`,
  );

  return { root, skillsDir, skills: skills.length, krnCommit, upstreamCommit: upstreamPin.commit };
}

export function checkSkills({ root }) {
  const errors = [];
  const warnings = [];
  const skillsDir = path.join(root, ".agents", "skills");
  if (!fs.existsSync(skillsDir)) {
    return { root, skills: 0, budget: 0, errors: ["`.agents/skills` is missing"], warnings };
  }
  const markerFile = path.join(skillsDir, MARKER);
  if (!fs.existsSync(markerFile)) {
    errors.push(`\`${MARKER}\` is missing; this directory is not a generated export`);
  }
  const marker = fs.existsSync(markerFile) ? readJson(markerFile) : null;
  let total = 0;
  let count = 0;
  for (const entry of fs.readdirSync(skillsDir, { withFileTypes: true }).sort((left, right) => left.name.localeCompare(right.name))) {
    if (!entry.isDirectory()) continue;
    count += 1;
    const dir = path.join(skillsDir, entry.name);
    const skillFile = path.join(dir, "SKILL.md");
    if (!fs.existsSync(skillFile)) {
      errors.push(`${entry.name}: missing SKILL.md`);
      continue;
    }
    const fields = frontmatter(skillFile);
    if (!fields?.name || !fields?.description) {
      errors.push(`${entry.name}: SKILL.md needs name and description frontmatter`);
      continue;
    }
    if (fields.name !== entry.name) errors.push(`${entry.name}: frontmatter name "${fields.name}" must equal the directory name`);
    if (!fs.existsSync(path.join(dir, "agents", "openai.yaml"))) errors.push(`${entry.name}: missing agents/openai.yaml`);
    total += fields.name.length + fields.description.length;
    if (fields.description.length > 280) {
      warnings.push(`${entry.name}: description is ${fields.description.length} chars (informational; KRN-owned skills stay within 280)`);
    }
  }
  if (total > BUDGET) errors.push(`skill list costs ${total} characters of ${BUDGET}; prune, split scopes, or set allow_implicit_invocation: false`);
  const catalogFile = path.join(skillsDir, "README.md");
  const catalog = fs.existsSync(catalogFile) ? fs.readFileSync(catalogFile, "utf8") : "";
  if (!catalog) errors.push(".agents/skills/README.md is missing");
  if (marker) {
    for (const pin of [marker.krn?.commit, marker.upstream?.commit]) {
      if (!pin || !catalog.includes(pin)) errors.push(`.agents/skills/README.md is missing provenance pin ${pin ?? "?"}`);
    }
    const expected = marker.skills ?? [];
    if (marker.skills && expected.length !== count) errors.push(`marker lists ${expected.length} skills but ${count} directories exist`);
  }
  if (!fs.existsSync(path.join(skillsDir, "UPSTREAM-LICENSE"))) errors.push(".agents/skills/UPSTREAM-LICENSE is missing");

  return { root, skills: count, budget: total, errors, warnings };
}
